"""
Django settings for boutique_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i%^vc9v+ty5+trn34%_rgn58j-2w3jy#60h6z++3x_#k=_p5iu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# ==============================================================================
# CONFIGURACIÓN DE APLICACIONES INSTALADAS (INSTALLED_APPS)
# ==============================================================================
# Registra las aplicaciones nativas de Django y las aplicaciones locales creadas.
# Es indispensable registrar 'prendas' para que el ORM reconozca sus modelos y migraciones.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Aplicación local de Boutique
    'prendas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'boutique_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ruta absoluta hacia la carpeta templates en la raíz del proyecto
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boutique_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# ==============================================================================
# CONFIGURACIÓN DE BASE DE DATOS (DATABASES) - CONEXIÓN CON XAMPP (MARIADB/MYSQL)
# ==============================================================================
# Se sustituye el motor SQLite por 'django.db.backends.mysql'.
# Utiliza internamente el conector nativo 'mysqlclient' instalado previamente en el venv.
DATABASES = {
    'default': {
       # Motor de base de datos relacional MySQL/MariaDB
        'ENGINE': 'django.db.backends.mysql',
        # Nombre exacto de la base de datos creada previamente en phpMyAdmin
        'NAME': 'boutique_db',
        # Usuario predeterminado del servicio local en XAMPP
        'USER': 'root',
        # Contraseña vacía por defecto en instalaciones estándar de XAMPP
        'PASSWORD': '',
        # Dirección IP del servidor de base de datos local (localhost)
        'HOST': '127.0.0.1',
        # Puerto de conexión estándar para servicios MySQL/MariaDB
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
# ==============================================================================
# TIPO DE CLAVE PRIMARIA AUTOINCREMENTAL PREDETERMINADA
# ==============================================================================
# Define que los identificadores 'id' generados automáticamente utilicen BigAutoField (64 bits),
# evitando advertencias del sistema y garantizando escalabilidad en la base de datos.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'