# Generated by Django 5.0.14 on 2026-09-23 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Hoodie Oversize Essential', max_length=120, verbose_name='Nombre de la prenda')),
                ('codigo_sku', models.CharField(help_text='Identificador único del producto', max_length=30, unique=True, verbose_name='Código SKU')),
                ('categoria', models.CharField(choices=[('Poleras', 'Poleras'), ('Hoodies', 'Hoodies')], default='Poleras', max_length=20, verbose_name='Categoría')),
                ('talla', models.CharField(choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)')], default='M', max_length=5, verbose_name='Talla')),
                ('color', models.CharField(max_length=40, verbose_name='Color')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Precio ($CLP)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('imagen_url', models.URLField(blank=True, max_length=600, verbose_name='URL de Imagen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción y Material')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
